# Generated by Django 2.2.7 on 2019-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First Player to Move'), ('S', 'Second Player to Move'),
                                            ('W', 'First Player Wins'), ('L', 'Second Player Wins'), ('D', 'Draw')],
                                   default='F', max_length=1),
        ),
    ]
